//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionareEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public string Description { get; set; }
        public int Sorted { get; set; }
        public bool Correct { get; set; }
        public int ModifyBy { get; set; }
        public System.DateTime ModifyAt { get; set; }
        public int QuestId { get; set; }
    
        public virtual Quest Quest { get; set; }
    }
}
