// <auto-generated />
namespace QuestionareEntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Refer_Answer_Quest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Refer_Answer_Quest));
        
        string IMigrationMetadata.Id
        {
            get { return "201511091620483_Refer_Answer_Quest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
