// <auto-generated />
namespace QuestionareEntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class referer_answers_qustions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(referer_answers_qustions));
        
        string IMigrationMetadata.Id
        {
            get { return "201511100847517_referer_answers_qustions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
